export const AppTooltipKeys = {
  MAIN_SCREEN: 'MAIN_SCREEN_TOOLTIP',
  CREDENTIALS_SCREEN: 'CREDENTIALS_SCREEN_TOOLTIP',
  CONNECTIONS_SCREEN: 'CONNECTIONS_SCREEN_TOOLTIP',
  CREDENTIAL_DETAIL_SCREEN: 'CREDENTIAL_DETAIL_SCREEN_TOOLTIP',
} as const;
