arrowParens: 'avoid',
bracketSpacing: true
endOfLine: auto
bracketSameLine: true
jsxBracketSameLine: true
quoteProps: as-needed
semi: true
singleQuote: true
tabWidth: 2
trailingComma: es5
useTabs: false
printWidth: 100